### ISSUE TITLE
EDO -> infoResistances.c -> remarque / amélioration / bugs

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_PRJ2_23_24#19]
- [x] => bug / amélioration / question => librairie => quelle(s) librairie(s) devez-vous encore rajouter ? 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L16C1-L23C24

**FCT ControleChoixSerie**
- [x] => spécification / bug / amélioration / question => fonction => déclaration => paramètre de sortie => est-ce que cela correspond au CDC p.3 ? => voir #15 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L69
- [x]  => bug / amélioration / question => paramètre de sortie => type => key word => `return` => type => différence entre  `char`VS `e_validation` 
- [x] => spécification / bug / amélioration / question => instruction => respect du CDC p3 => instruction => afficher un msg => comment faites vous-cela ? et où ? 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L73C1-L90C3

**FCT ControleValR**
- [x] => spécification / bug / amélioration / question => fonction => déclaration => paramètre => entrée / sortie => que vous dit le CDC p.3 => #15
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L101
- [x] => bug / amélioration / question => algorithme => test/condition => opérateur logique => point de test => priorité => quelle est la priorité la plus grande entre  `>=` et `&&` ? 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L105
- [x] => bug / amélioration / question => type => `e_validation` => écriture => norme C => déclaration => instruction => pouvez-vous déclarer n'importe ou une variable ? 
- [x] => bug / amélioration / question => variable =>`validationResistance` => écriture => pouvez-vous écrire un même nom déclaré dans un même bloc 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L103C15-L103C36
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L107
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L111
- [x] => spécification / bug / amélioration / question => algorithme => voir le CDC p3 => message utilisateur => implémentation  ? 

**FCT ControlePoidPuissanceR**
- [x] => spécification / bug / amélioration / question => fonction => paramètre entrée => type => voir CDC p3 => respect du CDC ? 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L124
- [x] => bug / amélioration / question => algorithme => test/condition => opérateur logique => point de test => priorité => quelle est la priorité la plus grande entre  `>=` et `&&` ? 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L128
- [x] => bug / amélioration / question => type => `e_validation` => écriture => norme C => déclaration => instruction => pouvez-vous déclarer n'importe ou une variable ? 
- [x] => bug / amélioration / question => variable =>`validadationPuissanceR` => écriture => pouvez-vous écrire un même nom déclaré dans un même bloc 
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L126
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L130
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L134C17-L134C40
- [x] => spécification / bug / amélioration / question => algorithme => voir le CDC p3 => message utilisateur => implémentation  ? 

**FCT CalculRUser**
- [x] => bug / amélioration / question / spécification => fonction => déclaration => paramètre => entrée / sortie => que vous dit le CDC p.4 => voir issue #15
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L147C1-L150C3
- [x] => bug / amélioration / question / spécification => algorithme => voir le CDC p4 => !! non implémenté !! 

**FCT CalculValSerie**
- [ ] => bug / amélioration / question / spécification => fonction pas implémentée => voir le CDC p4
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L154C1-L160C87

**FCT CalculRNormalisee**
- [ ] => bug / amélioration / question / spécification => fonction pas implémentée => voir le CDC p4
https://github.com/PBYetml/PROG_SLO1_PRJ2_23_24/blob/d5ddc1140c066ff6dd44b345feb81ad499da3d23/EDO/TEST1_2_EDA/TEST1_2_EDA/infoResistances.c#L165C1-L172C87
